Fix multiple definition of types
Force type function to be static inline.

Because AFB_BINDING_X4R1_ITF_CURRENT_REVISION is 7,
the symbol AFB_PREDEFINED_TYPE_UUID were mapped to a repeated
function, causing link error:

ld: x.o: in function `_AFB_PREDEFINED_TYPE_UUID_':
afb-binding-x4.h:2667: multiple definition of `_AFB_PREDEFINED_TYPE_UUID_'; ...